language: java
sudo: false
script:
  - mvn clean package assembly:single
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - target/metadata-*.zip
  skip_cleanup: true
  on:
    tags: true
