# Basic settings configuration for metadata extension

# - Allow users to select "Custom FDP" connection and set baseURI, email, and
#   password on their own (not just from predefined list)
#   Do not set this to "false" when no fdpConnections are specified!
allowCustomFDP: true

# - You may pre-configure some metadata to appear prefilled in the metadata forms.
#   The keys should correspond with metadata form specs
metadata:
  language: http://id.loc.gov/vocabulary/iso639-1/en
  license: http://purl.org/NET/rdflicense/cc-by3.0
  publisher: http://publisher

# - Preconfigured FAIR Data Point connections
#   - Each connection should have name, baseURI, email, and password
#   - You can specify if should be pre-selected by "preselected" flag
fdpConnections:
  - name: 'My local FDP #01 (Albert Einstein)'
    baseURI: http://localhost
    email: albert.einstein@example.com
    password: password
    preselected: true
    metadata:
      language: http://id.loc.gov/vocabulary/iso639-1/en
      license: http://purl.org/NET/rdflicense/BSD2.0
      publisher: http://publisher-marek
      publisherName: Marek
  - name: 'My local FDP #01 (Nikola Tesla)'
    baseURI: http://localhost
    email: nikola.tesla@example.com
    password: password
