# Configuration of storages usable for storing FAIR data
#
# Each storage should have:
# name = String for its identification
# type = (one of: ftp, virtuoso, tripleStoreHTTP)
# enabled = flag if currently possible to use
# username & passwork = credentials for the storage (if applicable)
# host = URI of the storage
# directory = specification of location in the storage
# contentTypes (optional) = list of allowed content types
- name: Example FTP
  type: ftp
  enabled: true
  username: test
  password: example
  host: localhost
  directory: "/"
- name: Example Virtuoso
  type: virtuoso
  enabled: true
  username: dba
  password: virtDemo
  host: 127.0.0.1:8890
  directory: "/DAV/home/dba/rdf_sink/"
  contentTypes:
    - application/rdf+xml
    - application/x-turtle
    - text/turtle
- name: Local GraphDB
  type: tripleStoreHTTP
  enabled: true
  username: test
  password: pass
  host: localhost:7200
  directory: test01
  contentTypes:
    - application/rdf+xml
    - application/x-turtle
    - text/turtle
- name: Local AllegroGraph
  type: tripleStoreHTTP
  enabled: true
  username: test
  password: pass
  host: localhost:10035
  directory: test01
  contentTypes:
    - application/rdf+xml
    - application/x-turtle
    - text/turtle
