# Configuration of storages usable for storing FAIR data
#
# Each storage should have:
# name = String for its identification
# type = (one of: ftp, virtuoso, tripleStoreHTTP)
# enabled = flag if currently possible to use
# details for connections (may differ based on type):
# - username & password = credentials for the storage (if applicable)
# - host = URI of the storage
# - directory = specification of location in the storage
# - repository = in case of triple-stores
# contentTypes (optional) = list of allowed content types
- name: Example FTP
  type: ftp
  enabled: true
  details:
    username: test
    password: example
    host: localhost
    directory: "/"
- name: Example Virtuoso
  type: virtuoso
  enabled: true
  details:
    username: dba
    password: virtDemo
    host: 127.0.0.1:8890
    directory: "/DAV/home/dba/rdf_sink/"
  contentTypes:
    - application/rdf+xml
    - application/x-turtle
    - text/turtle
  maxByteSize: 12000
  filenamePatterns:
    - "*.xml"
    - "model_*.ttl"
- name: Local GraphDB
  type: tripleStoreHTTP
  enabled: true
  details:
    username: test
    password: pass
    host: localhost:7200
    repository: test01
  contentTypes:
    - application/rdf+xml
    - application/x-turtle
    - text/turtle
- name: Local AllegroGraph
  type: tripleStoreHTTP
  enabled: true
  details:
    username: test
    password: pass
    host: localhost:10035
    repository: test01
  contentTypes:
    - application/rdf+xml
    - application/x-turtle
    - text/turtle
